trigger:
  branches:
    include:
      - main

stages:
  - template: templates/terraform-validate.yml
    parameters:
      path: "./terraform"
      dependsOnStages: [ ]

  - template: templates/terraform-deploy.yml
    parameters:
      environment: prod
      gcpVariableGroupName: gcp-playground-prod
      path: "./terraform"
      dependsOnStages: [ Validate ]
